export interface KeyStroke {
  code: number;
  shift?: boolean;
}

const macLetters: Record<string, number> = {
  a: 0,
  s: 1,
  d: 2,
  f: 3,
  h: 4,
  g: 5,
  z: 6,
  x: 7,
  c: 8,
  v: 9,
  b: 11,
  q: 12,
  w: 13,
  e: 14,
  r: 15,
  y: 16,
  t: 17,
  o: 31,
  u: 32,
  i: 34,
  p: 35,
  l: 37,
  j: 38,
  k: 40,
  n: 45,
  m: 46,
};

const macChars: Record<string, KeyStroke> = {
  ...Object.fromEntries(Object.entries(macLetters).map(([key, code]) => [key, {code}])),
  ...Object.fromEntries(Object.entries(macLetters).map(([key, code]) => [key.toUpperCase(), {code, shift: true}])),
  '1': {code: 18},
  '2': {code: 19},
  '3': {code: 20},
  '4': {code: 21},
  '5': {code: 23},
  '6': {code: 22},
  '7': {code: 26},
  '8': {code: 28},
  '9': {code: 25},
  '0': {code: 29},
  ' ': {code: 49},
  '.': {code: 47},
  ',': {code: 43},
  '/': {code: 44},
  ';': {code: 41},
  "'": {code: 39},
  '[': {code: 33},
  ']': {code: 30},
  '\\': {code: 42},
  '-': {code: 27},
  '=': {code: 24},
  '!': {code: 18, shift: true},
  '@': {code: 19, shift: true},
  '#': {code: 20, shift: true},
  '$': {code: 21, shift: true},
  '%': {code: 23, shift: true},
  '^': {code: 22, shift: true},
  '&': {code: 26, shift: true},
  '*': {code: 28, shift: true},
  '(': {code: 25, shift: true},
  ')': {code: 29, shift: true},
  '_': {code: 27, shift: true},
  '+': {code: 24, shift: true},
  ':': {code: 41, shift: true},
  '"': {code: 39, shift: true},
  '<': {code: 43, shift: true},
  '>': {code: 47, shift: true},
  '?': {code: 44, shift: true},
};

const windowsChars: Record<string, KeyStroke> = {
  ...Object.fromEntries('abcdefghijklmnopqrstuvwxyz'.split('').map(ch => [ch, {code: ch.toUpperCase().charCodeAt(0)}])),
  ...Object.fromEntries('abcdefghijklmnopqrstuvwxyz'.split('').map(ch => [ch.toUpperCase(), {code: ch.toUpperCase().charCodeAt(0), shift: true}])),
  '0': {code: 48},
  '1': {code: 49},
  '2': {code: 50},
  '3': {code: 51},
  '4': {code: 52},
  '5': {code: 53},
  '6': {code: 54},
  '7': {code: 55},
  '8': {code: 56},
  '9': {code: 57},
  ' ': {code: 32},
  '.': {code: 190},
  ',': {code: 188},
  '/': {code: 191},
  ';': {code: 186},
  "'": {code: 222},
  '[': {code: 219},
  ']': {code: 221},
  '\\': {code: 220},
  '-': {code: 189},
  '=': {code: 187},
  '!': {code: 49, shift: true},
  '@': {code: 50, shift: true},
  '#': {code: 51, shift: true},
  '$': {code: 52, shift: true},
  '%': {code: 53, shift: true},
  '^': {code: 54, shift: true},
  '&': {code: 55, shift: true},
  '*': {code: 56, shift: true},
  '(': {code: 57, shift: true},
  ')': {code: 48, shift: true},
  '_': {code: 189, shift: true},
  '+': {code: 187, shift: true},
  ':': {code: 186, shift: true},
  '"': {code: 222, shift: true},
  '<': {code: 188, shift: true},
  '>': {code: 190, shift: true},
  '?': {code: 191, shift: true},
};

const shiftCode = process.platform === 'darwin' ? 56 : 16;

export const getKeyStroke = (char: string) => {
  return process.platform === 'darwin' ? macChars[char] : windowsChars[char];
};

export const getShiftKeyCode = () => shiftCode;
