name: Typechecking
on: [ workflow_call ]

concurrency:
  group: typechecking-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  typescript:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - run: timeout 20m npm ci --foreground-scripts
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
          PUPPETEER_SKIP_DOWNLOAD: 'true'

      - run: npm run typecheck:main
      - run: npm run typecheck:preload
      - run: npm run typecheck:renderer
